- name: "Check if easy_install is present"
  command: which easy_install
  register: easy_installed
  ignore_errors: True

- name: "Install ansible docker requirements"
  apt:
    name: python-setuptools
    state: installed
    update_cache: True
  when: easy_installed|failed

- name: "Check if pip is installed"
  command: which pip
  register: pip_installed
  ignore_errors: True

- name: "Install python pip"
  easy_install:
    name: pip
    state: latest
  when: pip_installed|failed

- name: "Install docker-py"
  pip:
    name: docker-py

