- name: "Install ansible docker requirements"
  apt:
    name: python-setuptools
    state: installed
    update_cache: True

- name: "Install python pip"
  easy_install:
    name: pip
    state: latest

- name: "Install docker-py"
  pip:
    name: docker-py

