- block:
  - name: "Create dockerfiles from templates without repositories"
    template:
      src: "{{ item.key }}.j2"
      dest: "/tmp/{{ item.key }}.dk"
    when: not item.value.has_key('notemplate') or
          item.value.notemplate == False
           
  - name: "Push git repositories"
    synchronize:
      src: "{{ item.value.repo }}"
      dest: /tmp/
    when: item.value.has_key('repo')
  
  - name: "Move templated Dockerfiles to their repositories"
    command: mv /tmp/{{ item.key }}.dk \
             /tmp/{{ item.value.repo }}/{{ item.value.image_path }}/{{ item.key }}.dk
    when: item.value.has_key('repo') and
          (not item.value.has_key('notemplate') or
            item.value.notemplate == False )
  
  - name: "Build images from templates"
    docker_image:
      name: "{{ item.value.tags[ansible_architecture] }}"
      repository: "{{ item.value.tags[ansible_architecture] }}"
      path: "/tmp/{{ item.value.repo|default('')|regex_replace('(^[^/]+/)+([^/]+)$','\\2') }}/{{ item.value.path|default('')}}"
      state: present
      force: True
      push: "{{ item.value.push_to_docker_hub }}"
      dockerfile: "/tmp/{{ item.value.repo|default('')|regex_replace('(^[^/]+/)+([^/]+)$','\\2') }}/{{ item.value.image_path|default('') }}/{{ item.key }}.dk"
  
  - name: "Clean up dockerfiles"
    file:
      name: "/tmp/{{ item.key }}.dk"
      state: absent
  
  - name: "Clean up repositories"
    file:
      name: "/tmp/{{ item.value.repo }}"
      state: absent
      directory_mode: True
    when: item.value.has_key('repo')
  tags: "images"
