- name: "Install ansible docker requirements"
  import_tasks: ansible_docker_requirements.yml
  become: True
  tags: always

- name: "Install docker"
  import_tasks: requirements.yml
  become: True
  tags: docker_all_install

- name: "Log into DockerHub"
  tags:
    - images
    - multiarch
    - pull
    - clean
  become: True
  command: docker login -u {{ docker_login.user }} -p {{ docker_login.password }}

- name: "Clean docker images"
  include_tasks: clean_docker_images.yml
  become: True
  tags: clean
  with_dict: "{{ IMAGE_DATA | combine(MANIFEST_IMAGES) }}"
  when: item.key in BUILD

- name: "Build images"
  include_tasks: build_images.yml
  become: True
  tags: 'images'
  with_dict: "{{ IMAGE_DATA }}"
  when: item.key in BUILD and
        ansible_architecture in BUILD[item.key].tags and
        item.value.tags.has_key(ansible_architecture)

- name: "Pull images"
  include_tasks: docker_pull.yml
  become: True
  tags:
    - 'pull'
    - 'multiarch'
  with_dict: "{{ IMAGE_DATA | combine(MANIFEST_IMAGES) }}"

- name: "Build manifests"
  include_tasks: build_manifests.yml
  tags: 'multiarch'
  with_dict: "{{ IMAGE_DATA | combine(MANIFEST_IMAGES) }}"
  when: ansible_architecture == "x86_64" and
        image.key in BUILD and
        "'multiarch' in image.value.tags" and
        push_to_docker_hub == True
        #^ No sense in creating manifests if we can't download
        #the corresponding images
  loop_control:
    loop_var: image
